name: Trigger Workflows

on:
  schedule:
    - cron: "30 18 * * *" # 12:00 AM IST (midnight)
  workflow_dispatch: # Using https://console.cron-job.org for schedule

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check for update
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'check-for-update',
              client_payload: {}
            })